### ISSUE TITLE
Images aren't shown in the Confluence Gallery when migrating from Confluence

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#248] opened 2024-04-23 14:15 UTC
Steps to reproduce:

1. Have a document in Confluence with Gallery ex. https://xwikisas.atlassian.net/wiki/spaces/FOS/pages/570032383/Gallery and export is as XML
2. Migrate the document in xwiki following the steps from [Confluence Migrator Application (Pro)](https://store.xwiki.com/xwiki/bin/view/Extension/Confluence%20Migrator%20Application%20%28Pro%29/#HPrerequisites)
3. From Navigation click on the migrated space and select the page

Expected results: The images appear in the xwiki page as added in Confluence.

Actual results: The images don't appear at all in the xwiki page, only as attachments,

![Gallery1](https://github.com/xwikisas/xwiki-pro-macros/assets/40691112/41cf3247-47c6-414a-a748-e1666f365410)

![GalleryInSource](https://github.com/xwikisas/xwiki-pro-macros/assets/40691112/faf61dc7-28f2-443c-ba4c-356cd09796c0)

Environment: Windows 11, XWiki Cloud 15.10.8, Chrome 123, Pro Macros 1.16.5

**Comment by Farcasut** [comment] 2024-06-19 09:09
I can't reproduce the issue anymore, probably fixed with recent improvements on the migrator
![image](https://github.com/xwikisas/xwiki-pro-macros/assets/92780090/f5c86a89-1db3-4c1b-8224-7304b6ab0ea7)

**Closed by Farcasut** 2024-06-19 09:09 UTC
Labels: Priority: Critical, Type: Bug, Macro: Gallery
